### ISSUE TITLE
"export 'createStore' was not found in 'vuex'

### ISSUE THREAD

**Issue by TheyGiveMeMoney** [daniel-farina/vuejs-dapp-boilerplate#1]
yarn install lead to 
"export 'createStore' was not found in 'vuex'
when calling yarn serve for me at least

**Comment by daniel-farina** [comment]
> yarn install lead to
> "export 'createStore' was not found in 'vuex'
> when calling yarn serve for me at least

I think maybe you have Vuex3 in your system. Install Vuex 4 and remove 3 if you already have it in your system
```
npm uninstall --save vuex
yarn add vuex@next
```
https://stackoverflow.com/questions/65150323/vue-js-3-export-createstore-was-not-found-in-vuex

Thanks, I added it to the README. 

also make sure to pull the latest changes, I added some network configurations to make it easy to customize with custom networks.

**Comment by TheyGiveMeMoney** [comment]
Thanks for this, closing THUMBSUP!
